name: Generate Auth token
description: Uses the DnD-Mapp GitHub Authentication App to generate a token for authenticating and authorizing Git actions.
outputs:
    token:
        description: The authentication token
        value: ${{ steps.generate-token.outputs.token }}
runs:
    using: composite
    steps:
        - name: Generate token
          id: generate-token
          uses: actions/create-github-app-token@v2
          with:
              app-id: ${{ secrets.AUTH_APP_ID }}
              private-key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
