name: Build
permissions:
    contents: read
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    build-and-test:
        name: Build & Test
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: dnd-mapp/actions/setup-node@main
            - name: Install dependencies
              run: npm ci
            - name: Check linting
              run: npm run lint
            - name: Check formatting
              run: npm run format:check
            - name: Compile code
              run: npm run build
            - name: Run tests
              run: npm run test
