name: Deploy Storybook
permissions:
    contents: write
on:
    release:
        types:
            - released
jobs:
    deploy-storybook:
        name: Deploy Storybook
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: ./.github/actions/setup-node
            - name: Install dependencies
              run: npm ci
            - name: Compile code
              run: npm run build
            - name: Build storybook
              run: npm run build-storybook
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: dist/storybook-static
