name: Publish
on:
    release:
        types:
            - released
jobs:
    publish:
        name: Publish package
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: ./.github/actions/setup-node
            - name: Install dependencies
              run: npm ci
            - name: Compile code
              run: npm run build
            - name: Publish
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
