name: Release
permissions:
    contents: write
on:
    pull_request:
        types:
            - closed
jobs:
    release:
        name: Create release
        runs-on: ubuntu-22.04

        # Make sure that publishing of the release is done is only after successful merge of a 'release/*' branch.
        if: startsWith(github.head_ref, 'release/') && github.event.pull_request.merged == true
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Extract version
              uses: ./.github/actions/extract-version
            - name: Configure Git
              uses: ./.github/actions/configure-git
            - name: Generate token
              id: generate-token
              uses: ./.github/actions/generate-auth-token
              with:
                  app-id: ${{ secrets.AUTH_APP_ID }}
                  private-key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
            - name: Create Git tag
              run: git tag -a ${{ env.VERSION }} -m "${{ env.VERSION }}"
              env:
                  GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
            - name: Push Git tag
              run: git push origin ${{ env.VERSION }}
              env:
                  GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
            - name: Publish the release
              uses: softprops/action-gh-release@v2
              with:
                  name: ${{ env.VERSION }}
                  tag_name: ${{ env.VERSION }}
                  token: ${{ steps.generate-token.outputs.token }}
